  %% SetAudioInterface
switch sAudioInterface
  case 'Babyface' % RME Babyface (stereo output)
    sAudioDevice    = 'ASIO Fireface USB';
    fileReader      = audioDeviceReader('Driver','ASIO','Device',sAudioDevice,...
      'SamplesPerFrame',frameLength,'NumChannels',iNoTx,'SampleRate',44.1e3);
%       'SamplesPerFrame',frameLength,'NumChannels',iNoTx,'SampleRate',48e3);
    deviceWriterHeadphone   = audioDeviceWriter('Device',sAudioDevice,...
      'Driver','ASIO','SampleRate',fileReader.SampleRate,'BufferSize',32);
    deviceWriterSpeaker     = audioDeviceWriter('Device',sAudioDevice,...
      'Driver','ASIO','SampleRate',fileReader.SampleRate,'BufferSize',32);
    set(fileReader,...
      'ChannelMappingSource','Property','ChannelMapping',6+[1:iNoTx]);
    set(deviceWriterHeadphone,...
      'ChannelMappingSource','Property','ChannelMapping',10+[1,2]);
    set(deviceWriterSpeaker,...
      'ChannelMappingSource','Property','ChannelMapping',6+[1:iNoTx]);
    
  case 'Fireface'  % RME Fireface (surround)
    sAudioDevice    = 'ASIO Fireface USB';
    fileReader      = audioDeviceReader('Driver','ASIO','Device',sAudioDevice,...
      'SamplesPerFrame',frameLength,'NumChannels',iNoTx);
    deviceWriterHeadphone   = audioDeviceWriter('Device',sAudioDevice,...
      'Driver','ASIO','SampleRate',fileReader.SampleRate,'BufferSize',32);
    deviceWriterSpeaker     = audioDeviceWriter('Device',sAudioDevice,...
      'Driver','ASIO','SampleRate',fileReader.SampleRate,'BufferSize',32);
    set(fileReader,...
      'ChannelMappingSource','Property','ChannelMapping',10+[1:iNoTx]);
    set(deviceWriterHeadphone,...
      'ChannelMappingSource','Property','ChannelMapping',[17,18]);
    set(deviceWriterSpeaker,...
      'ChannelMappingSource','Property','ChannelMapping',10+[1:iNoTx]);
    
  case 'Banana'  % Arbitrary sound interface
%     sAudioReader    = 'Voicemeeter AUX Virtual ASIO';
%     sAudioWriter    = 'Voicemeeter AUX Virtual ASIO';
    sAudioReader    = 'Voicemeeter Virtual ASIO';
    sAudioWriter    = 'Voicemeeter Virtual ASIO';
    fileReader      = audioDeviceReader('Driver','ASIO','Device',sAudioReader,...
      'SamplesPerFrame',frameLength,'NumChannels',iNoTx);
    switch iNoTx
      case 2
        set(fileReader,...
        'ChannelMappingSource','Property','ChannelMapping',[1:2]);
      case 6
        set(fileReader,...
        'ChannelMappingSource','Property','ChannelMapping',[1:4,7,8]);
    end
    deviceWriterHeadphone   = audioDeviceWriter('Driver','ASIO','Device',sAudioWriter,...
      'SampleRate',fileReader.SampleRate,'BufferSize',1024);
    set(deviceWriterHeadphone,...
      'ChannelMappingSource','Property','ChannelMapping',[5:6]);
    deviceWriterSpeaker     = audioDeviceWriter('Driver','ASIO','Device',sAudioWriter,...
      'SampleRate',fileReader.SampleRate,'BufferSize',1024);    
    set(deviceWriterSpeaker,...
      'ChannelMappingSource','Property','ChannelMapping',[5:6]);
    
  otherwise
    warning('No valid audio interface selected');
end

% start with
deviceWriterActive = deviceWriterHeadphone;